allowBuilds:
  core-js: false
  unrs-resolver: false

autoDedupe: true

autoInstallPeers: false

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "ember-testem"

packages:
  - "packages/**"
  - "tests/**"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*stylelint*"

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: "warn"
